### ISSUE TITLE
Random UDP package DoS network system

### ISSUE THREAD

**Issue by o01eg** [amethyst/laminar#202]
I've tried to open UDP socket and send something here via `nc` and got panic in the networking thread:

```
thread '<unnamed>' panicked at 'not yet implemented: Packet ID 49 does not exist yet.', /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/laminar-0.2.3/src/packet/enums.rs:90:18
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
stack backtrace:
   0: std::sys::unix::backtrace::tracing::imp::unwind_backtrace
             at src/libstd/sys/unix/backtrace/tracing/gcc_s.rs:39
   1: std::sys_common::backtrace::print
             at src/libstd/sys_common/backtrace.rs:71
             at src/libstd/sys_common/backtrace.rs:59
   2: std::panicking::default_hook::{{closure}}
             at src/libstd/panicking.rs:197
   3: std::panicking::default_hook
             at src/libstd/panicking.rs:211
   4: std::panicking::rust_panic_with_hook
             at src/libstd/panicking.rs:474
   5: std::panicking::continue_panic_fmt
             at src/libstd/panicking.rs:381
   6: std::panicking::begin_panic_fmt
             at src/libstd/panicking.rs:336
   7: <laminar::packet::enums::PacketType as laminar::packet::EnumConverter>::from_u8
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/laminar-0.2.3/src/packet/enums.rs:90
   8: <laminar::packet::header::standard_header::StandardHeader as laminar::packet::header::header_reader::HeaderReader>::read
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/laminar-0.2.3/src/packet/header/standard_header.rs:99
   9: laminar::packet::packet_reader::PacketReader::read_standard_header
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/laminar-0.2.3/src/packet/packet_reader.rs:36
  10: laminar::net::virtual_connection::VirtualConnection::process_incoming
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/laminar-0.2.3/src/net/virtual_connection.rs:195
  11: laminar::net::socket::Socket::recv_from
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/laminar-0.2.3/src/net/socket.rs:169
  12: laminar::net::socket::Socket::start_polling
             at /home/o01eg/.cargo/registry/src/github.com-1ecc6299db9ec823/laminar-0.2.3/src/net/socket.rs:69
  13: amethyst_network::server::host::Host::run::{{closure}}
             at /home/o01eg/.cargo/git/checkouts/amethyst-fedb0a1032a075ce/aa4b4ab/amethyst_network/src/server/host.rs:29
```

After panic port was closed. In the case of public game servers it could lead to very simple DoS.

**Comment by BourgondAries** [comment]
This packet should just be dropped, instead of panicking. We really shouldn't panic on faulty headers

**Comment by BourgondAries** [comment]
This should be closed as we now have a fuzzing test for this that succeeds.
