### ISSUE TITLE
Tests not failing on panic

### ISSUE THREAD

**Issue by LucioFranco** [amethyst/laminar#71]
```
thread 'thread 'check_for_timeoutscheck_for_timeouts' panicked at '' panicked at 'thread 'Unable to send disconnect event: "SendError(..)"Unable to send disconnect event: "SendError(..)"check_for_timeouts', thread '', ' panicked at 'check_for_timeoutsUnable to send disconnect event: "SendError(..)"' panicked at 'libcore/result.rs', libcore/result.rsUnable to send disconnect event: "SendError(..)":libcore/result.rs:', 1009:1009libcore/result.rs:1009::5:51009
5
:note: Run with `RUST_BACKTRACE=1` for a backtrace.

5
thread 'check_for_timeouts' panicked at 'Unable to send disconnect event: "SendError(..)"', libcore/result.rs:1009:5
thread 'check_for_timeouts' panicked at 'Unable to send disconnect event: "SendError(..)"', libcore/result.rs:1009:5
```

I am getting this panic when running the tests locally. But the tests still all pass 🤔

**Comment by TimonPost** [comment]
Is this still an issue I can not reproduce this.
